site_name: Bases de Datos - Tema 2
site_url: https://BDPuebla.github.io/tema2
theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
extra_css:
  - css/styles.css
nav:
  - Home: index.md
  - Introducción: introduccion.md
  - Modelado de datos: 
      - Modelado: modelado.md
      - Entidad-relacion: entidad-relacion.md
      - Entidades y relaciones: entidades-relaciones.md
      - Tipos de relaciones: tipos-relaciones.md
      - Atributos y Claves: atributos.md
      - Ejercicios de Diagramas E/R: diagramas.md
      - Diagrama E/R extendido: diagrama-extendido.md
  - Paso a tablas:
      - Introducción: paso-tablas-introduccion.md
      - Proceso: paso-tablas-proceso.md
      - Modelo Relacional: paso-tablas-modelo-relacional.md
  - Referencias: referencias.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2026 Víctor Suárez. IES Puebla de Vicar.  